namespace Philiprehberger.PasswordStrength;

/// <summary>
/// Contains a set of the top 1000 most commonly used passwords for detection purposes.
/// </summary>
internal static class CommonPasswords
{
    private static readonly HashSet<string> Passwords = new(StringComparer.OrdinalIgnoreCase)
    {
        "123456", "password", "12345678", "qwerty", "123456789", "12345", "1234",
        "111111", "1234567", "dragon", "123123", "baseball", "abc123", "football",
        "monkey", "letmein", "shadow", "master", "666666", "qwertyuiop", "123321",
        "mustang", "1234567890", "michael", "654321", "superman", "1qaz2wsx",
        "7777777", "121212", "000000", "qazwsx", "123qwe", "killer", "trustno1",
        "jordan", "jennifer", "zxcvbnm", "asdfgh", "hunter", "buster", "soccer",
        "harley", "batman", "andrew", "tigger", "sunshine", "iloveyou", "2000",
        "charlie", "robert", "thomas", "hockey", "ranger", "daniel", "starwars",
        "klaster", "112233", "george", "computer", "michelle", "jessica", "pepper",
        "1111", "zxcvbn", "555555", "11111111", "131313", "freedom", "777777",
        "pass", "maggie", "159753", "aaaaaa", "ginger", "princess", "joshua",
        "cheese", "amanda", "summer", "love", "ashley", "nicole", "chelsea",
        "biteme", "matthew", "access", "yankees", "987654321", "dallas", "austin",
        "thunder", "taylor", "matrix", "mobilemail", "mom", "monitor", "monitoring",
        "montana", "moon", "moscow", "password1", "password12", "password123",
        "passwd", "paste", "patrick", "paul", "penguin", "peter", "phantom",
        "phoenix", "piercing", "pilot", "pink", "pipeline", "pirate", "plaster",
        "platinum", "playboy", "player", "please", "poison", "police", "porsche",
        "power", "predator", "premium", "president", "prince", "private", "program",
        "project", "protection", "public", "punisher", "purple", "pussycat",
        "qazwsxedc", "queen", "rabbit", "rachel", "racing", "rafael", "rainbow",
        "random", "raider", "raven", "reality", "rebecca", "redskins", "register",
        "remember", "rescue", "richard", "river", "robert1", "roberto", "rocket",
        "roger", "romeo", "rookie", "rosebud", "runner", "rush2112", "russia",
        "rusty", "samantha", "sandra", "saturn", "scooby", "scorpio", "scorpion",
        "scott", "secret", "security", "serial", "service", "shadow1", "shannon",
        "shark", "sheila", "shelby", "shelly", "sherlock", "shield", "shit",
        "shopping", "sierra", "signal", "silver", "simone", "simple", "simpson",
        "single", "skippy", "slayer", "slider", "slipknot", "snake", "sniper",
        "snowball", "snyder", "soldier", "sophia", "sparky", "special", "spencer",
        "spider", "spiderman", "spirit", "sprint", "squirt", "srinivas", "stanley",
        "starter", "status", "stella", "steve", "stinger", "storm", "stupid",
        "success", "suckme", "summer1", "sunshine1", "superfly", "superman1",
        "support", "surfer", "swimming", "switch", "sydney", "system", "talent",
        "taurus", "teddy", "tennis", "teresa", "terminal", "test", "testing",
        "texas", "thailand", "theresa", "thomas1", "thx1138", "tiffany", "tiger",
        "tigers", "tigger1", "timber", "timothy", "tinker", "tobias", "tomcat",
        "topdog", "topgun", "toyota", "travis", "treasure", "trevor", "trinity",
        "tropical", "trouble", "truck", "truman", "trumpet", "tucker", "tuesday",
        "turbo", "turtle", "twitter", "tyler", "united", "universal", "unix",
        "unknown", "upload", "vader", "valentine", "vampire", "vanessa", "victor",
        "victoria", "video", "viking", "vincent", "violet", "viper", "virginia",
        "virtual", "vision", "visual", "volcano", "voyager", "walter", "warrior",
        "welcome", "whatever", "wheels", "whiskey", "white", "william", "willie",
        "wilson", "winner", "winston", "winter", "wizard", "wolf", "wolverine",
        "women", "wonder", "workshop", "world", "wright", "xavier", "yamaha",
        "yankee", "yellow", "young", "zeppelin", "zero", "zigzag", "zombie",
        "abcdef", "abcdefg", "abcd1234", "admin", "admin123", "administrator",
        "angel", "apple", "backup", "bailey", "banana", "basketball", "bella",
        "black", "blahblah", "blessed", "blue", "bond007", "boomer", "brandon",
        "braves", "broncos", "brooklyn", "brothers", "bubba", "buddy", "butter",
        "butterfly", "button", "calendar", "calling", "calvin", "camaro", "camera",
        "campbell", "canada", "captain", "cardinal", "carolina", "carpet", "cascade",
        "casper", "castle", "catalog", "catch22", "catherine", "celtic", "center",
        "champion", "change", "channel", "charles", "charlie1", "charlotte",
        "cherokee", "chester", "chicago", "chicken", "china", "chocolate", "chris",
        "christian", "christmas", "church", "claire", "clark", "classic", "claude",
        "clinton", "close", "cluster", "cobra", "coconut", "coffee", "college",
        "colorado", "columbia", "columbine", "comcast", "compact", "company",
        "complex", "connect", "control", "cookie", "cool", "cooper", "copper",
        "corvette", "cotton", "country", "cougar", "cowboys", "coyote", "craig",
        "creative", "cricket", "crystal", "cupcake", "curtis", "custom", "cypress",
        "dakota", "dancer", "danger", "database", "david", "dealer", "december",
        "defense", "delta", "derek", "design", "detroit", "dexter", "diamond",
        "diesel", "digital", "direct", "discover", "disney", "doctor", "dodger",
        "dollar", "dolphin", "donald", "douglas", "driver", "eagle", "eagles",
        "edward", "einstein", "electric", "elephant", "elizabeth", "energy",
        "engine", "english", "enterprise", "escape", "espresso", "europa",
        "evolution", "explorer", "express", "extreme", "falcon", "family",
        "fantasy", "fashion", "favorite", "felix", "ferrari", "fiction", "finder",
        "firefox", "florida", "flower", "forest", "forever", "formula", "fortune",
        "forward", "foster", "fountain", "france", "francis", "frank", "franklin",
        "friends", "frogger", "frontier", "gabriel", "galaxy", "gandalf", "garden",
        "garrett", "gateway", "general", "genesis", "genius", "gerald", "germany",
        "ghost", "gibson", "gizmo", "global", "golden", "goldfish", "gordon",
        "grace", "graham", "granite", "green", "gregory", "griffin", "guitar",
        "gunner", "hammer", "hampton", "hannah", "happy", "harbor", "harold",
        "harrison", "harvest", "hawaii", "heaven", "hello", "hellos", "henry",
        "hercules", "herman", "hershey", "holiday", "hollywood", "honda",
        "horizon", "hornet", "houston", "howard", "hunter1", "husker", "iceman",
        "imagine", "imperial", "india", "indian", "indiana", "infinity",
        "insane", "inspire", "install", "intel", "island", "jackson", "jacob",
        "jaguar", "jamaica", "james", "japan", "jasmine", "jason", "jasper",
        "jersey", "john", "johnny", "johnson", "joseph", "judge", "juice",
        "juliet", "jumper", "jungle", "junior", "jupiter", "justice", "kansas",
        "karma", "kelly", "kennedy", "kevin", "kingdom", "kitten", "knight",
        "kodiak", "lambda", "lancelot", "laser", "lauren", "leader", "legend",
        "lemon", "leonard", "leopard", "liberty", "light", "lincoln", "lion",
        "lionel", "little", "london", "longhorn", "lucky", "luther", "machine",
        "maddog", "madison", "madonna", "magic", "maiden", "mango", "marathon",
        "marcus", "marine", "marlboro", "marshall", "martin", "marvin",
        "maximus", "maxwell", "member", "memphis", "mercedes", "mercury",
        "merlin", "method", "midnight", "miller", "million", "mission",
        "mitchell", "moose", "morgan", "morning", "morris", "mother", "mountain",
        "murphy", "murray", "music", "mustang1", "nancy", "napoleon", "nation",
        "nature", "nautilus", "nelson", "neptune", "network", "nevada", "newton",
        "nirvana", "nissan", "norman", "norton", "nothing", "november", "nugget",
        "number", "nutmeg", "oakland", "ocean", "october", "oliver", "omega",
        "online", "open", "oracle", "orange", "orchid", "oregon", "oscar",
        "osiris", "pacific", "pacific1", "packer", "packers", "palace", "palmer",
        "pamela", "panther", "paradise", "parker", "pascal", "passport",
        "peaches", "peanut", "pearl", "pegasus", "people"
    };

    /// <summary>
    /// Determines whether the specified password is in the common passwords list.
    /// </summary>
    /// <param name="password">The password to check.</param>
    /// <returns><c>true</c> if the password is common; otherwise, <c>false</c>.</returns>
    internal static bool Contains(string password)
    {
        return Passwords.Contains(password);
    }
}
